### PR TITLE
GameData Revision + Detour

### PR DESCRIPTION
**Pull request by Kenzzer**
- Backported my calculation of EquipWearable from VSH-Rewrite thus reducing the size of the gamedata.
- Fetch RemoveWearable offset from official SM gamedata instead of szf
- Memory patching the function `CGameUI::Deactivate` to avoid a crash when disabled without a valid activator entity.

PR made on request from @Alex-Turtle
Note: memory patch untested on linux

### CODE REVIEW

**Comment by Kenzzer** [comment]
That's is indeed scary. But detours are also basically that. Memory patches are preferable over detours, it avoids the use of `dhooks` and/or allow other plugins/extensions to detour this function for their own purposes without risking a crash.

Although to be fair, I don't see why `CGameUI::Deactivate` would be detoured by another plugin, but `szf`.
The choice was originally made because of @Dispenz0r, I offered detour or patch. Patch was picked to avoid using `dhooks`. If it is really necessary then all that is needed is to overwrite the activator pointer to any valid CBaseEntity pointer. (i.e `world` 0` would be just fine) The state of `m_player` is meaningless, so no need to look for its offset.

Let me know, and I'll do the appropriate changes.

**Comment by FortyTwoFortyTwo** [comment]
> That's is indeed scary. But detours are also basically that. Memory patches are preferable over detours, it avoids the use of `dhooks` and/or allow other plugins/extensions to detour this function for their own purposes without risking a crash.

Memory patch can also potentially break if more than 1 plugins use it, but won't crash so eh.
Don't really see why `dhooks` should be avoided when SZF already uses it and almost every server have ext. Detour support though, server may or may not have it, and SZF don't have one yet.

> If it is really necessary then all that is needed is to overwrite the activator pointer to any valid CBaseEntity pointer. (i.e world 0 would be just fine) The state of m_player is meaningless, so no need to look for its offset.
That is true as it really only used for a warning nobody cares about, would've gone for that.

**Comment by Kenzzer** [comment]
> Don't really see why `dhooks` should be avoided when SZF already uses it and almost every server have ext. Detour support though, server may or may not have it, and SZF don't have one yet.

That is exactly the reason, not all servers use `dhooks + detours`. At the end of the day, it all boils down to preferences. However more servers should use detours, so maybe it should be enforced.
I'll convert the memory patch to a detour.

**Comment by Kenzzer** [comment]
Alright, the memory patch has been changed to a detour.
And links have been updated in `README.md` & `install.sh`.

This build, however, hasn't been tested, but should theoretically work. I don't have TF2, so somebody from this repository will have to test.

**Comment by FortyTwoFortyTwo** [comment]
Tried it out, dhook strangely doesn't like entity passed into `DHookSetParam`. Tried different entities as-well and got no luck.

```
L 04/21/2020 - 13:52:52: [SM] Exception reported: Invalid entity index passed for param value
L 04/21/2020 - 13:52:52: [SM] Blaming: disabled\superzombiefortress.smx
L 04/21/2020 - 13:52:52: [SM] Call stack trace:
L 04/21/2020 - 13:52:52: [SM]   [0] DHookSetParam
L 04/21/2020 - 13:52:52: [SM]   [1] Line 4578, superzombiefortress.sp::Detour_CGameUI_Deactivate
```

**Comment by Kenzzer** [comment]
> Tried it out, dhook strangely doesn't like entity passed into `DHookSetParam`. Tried different entities as-well and got no luck.

Hmm, well we can opt for the dangerous solution then. I'll make a new commit editing the detour.

**Pull request merged**
